### ISSUE TITLE
The act of logging produces more logs, causing an infinite loop

### ISSUE THREAD

**Issue by adeschamps** [hlb8122/tracing-gelf#10]
It seems that, when trace logs are enabled, the act of sending logs to Graylog itself produces logs. Since those logs will then be sent to Graylog..... we get an infinite loop!

```
2021-06-23T18:38:56.659250405+00:00 TRACE tokio_util::codec::framed_impl: writing; remaining=1002    
2021-06-23T18:38:56.659386680+00:00 TRACE tokio_util::codec::framed_impl: framed transport flushed    
2021-06-23T18:38:56.659539752+00:00 TRACE tokio_util::codec::framed_impl: flushing framed transport    
2021-06-23T18:38:56.659673413+00:00 TRACE tokio_util::codec::framed_impl: writing; remaining=1002    
2021-06-23T18:38:56.659808685+00:00 TRACE tokio_util::codec::framed_impl: framed transport flushed    
2021-06-23T18:38:56.659961482+00:00 TRACE tokio_util::codec::framed_impl: flushing framed transport    
```

I'm currently addressing this by filtering out any logs from `tokio_util`, which is fine for my use case. I'm not sure whether there's a technical solution to this, or if it should just be mentioned in the docs.

**Comment by hawkw** [comment]
`tracing` solves this problem by unsetting the default subscriber while inside of a call to a subscriber method, so logging from inside libraries used by the subscriber are automatically ignored. That doesn't help here, though, because these logs are coming from a background task that the subscriber talks to.

However, we could use a similar technique to what `tracing` does. If we wrap the background task's future in [`tracing_futures`'s `with_subscriber` combinator](https://docs.rs/tracing-futures/0.2.5/tracing_futures/trait.WithSubscriber.html#method.with_subscriber) using a subscriber that ignores everything, any logs emitted inside the background task will be ignored, rather than causing more logs to be sent. We don't even _have_ to use a subscriber that ignores every event there, we could even log events that occur on the background task to the console or something.

`tracing_core` [contains a `Subscriber` implementation that does nothing](https://github.com/tokio-rs/tracing/blob/807bc8fae777e7e55147a7d21d547500037fd7ec/tracing-core/src/dispatcher.rs#L664-L688), but it's currently not part of the public API. However, it would be fine to just copy and paste the code for now. We could also open an upstream issue for adding the `NoSubscriber` type to the public API...but I think it's pretty trivial to implement.
